name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.1.0

      - name: Setup Python
        uses: actions/setup-python@v7.0.0
        with:
          python-version: "3.14"

      - name: Run KFC script
        run: python .github/scripts/kfc.py
