name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.1.0

      - name: Run a one-line script
        run: echo Hello, world!


  KFC:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.1.0

      - name: Setup Python
        uses: actions/setup-python@v7.0.0
        with:
          python-version: "3.14"

      - name: Run KFC script
        run: python .github/scripts/kfc.py
  
  TEST:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-group: [1, 2, 3]

    steps:
      - name: Run Test ${{ matrix.test-group }}
        run: echo Test group ${{ matrix.test-group }}

  DEPLOY:
    needs: [KFC, TEST]
    runs-on: ubuntu-latest
  
    steps:
      - name: Run Deploy
        run: echo Deploy
